# Generated by Django 2.1 on 2018-08-23 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0003_auto_20180821_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='bus_day_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promise',
            name='end',
            field=models.DateField(default=models.DateField()),
        ),
    ]
