# Generated by Django 2.1 on 2018-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0004_auto_20180823_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='replace',
            field=models.IntegerField(default=1),
        ),
    ]
