# Generated by Django 2.1 on 2018-08-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0005_promise_replace'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='replace_status',
            field=models.IntegerField(choices=[(1, '일반대체'), (2, '매직 데이대체')], default=0),
        ),
        migrations.AlterField(
            model_name='promise',
            name='replace',
            field=models.FloatField(),
        ),
    ]
