# Generated by Django 2.1 on 2018-08-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0006_auto_20180824_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='replace',
        ),
        migrations.AddField(
            model_name='promise',
            name='replace_day',
            field=models.FloatField(default=0),
        ),
    ]
