# Generated by Django 2.1 on 2018-08-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0007_auto_20180824_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='replace_day',
            field=models.FloatField(),
        ),
    ]
