# Generated by Django 2.1 on 2018-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0008_auto_20180830_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='replace_status',
        ),
        migrations.AlterField(
            model_name='promise',
            name='replace_day',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promise',
            name='status',
            field=models.IntegerField(choices=[(1, '풀타임'), (2, '오전 반차'), (3, '오후 반차')], default=0),
        ),
    ]
