# Generated by Django 2.1 on 2018-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0010_auto_20180830_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='bus_day_count',
            field=models.IntegerField(default=0),
        ),
    ]
