# Generated by Django 2.1 on 2018-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0012_auto_20180830_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='reason',
            field=models.IntegerField(choices=[(1, '매직데이')], default=0),
        ),
    ]
