# Generated by Django 2.1 on 2018-08-31 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datepick', '0013_promise_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('used', models.FloatField(default=0.0)),
                ('available', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='promise',
            name='bus_day_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promise',
            name='reason',
            field=models.CharField(choices=[('매직데이', '매직데이')], max_length=100),
        ),
    ]
