# Generated by Django 2.1 on 2018-08-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0014_auto_20180831_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='status',
            field=models.IntegerField(choices=[(0, '일반'), (1, '하루 풀타임'), (2, '오전 반차'), (3, '오후 반차'), (4, '특별 휴가'), (5, '대체 근무')], default=0),
        ),
    ]
