# Generated by Django 2.1 on 2018-08-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0016_auto_20180831_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='regi_status',
            field=models.IntegerField(default=1),
        ),
    ]
