# Generated by Django 2.1 on 2018-09-03 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datepick', '0018_auto_20180831_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promise',
            new_name='Vacation',
        ),
    ]
