# Generated by Django 2.1 on 2018-09-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0020_remove_vacation_replace_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationhistory',
            name='replace_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='special_day',
            field=models.FloatField(default=0.0),
        ),
    ]
