# Generated by Django 2.1 on 2018-09-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0021_auto_20180904_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationhistory',
            old_name='available',
            new_name='replace_workday',
        ),
        migrations.RenameField(
            model_name='vacationhistory',
            old_name='replace_day',
            new_name='thisyear_left',
        ),
        migrations.RenameField(
            model_name='vacationhistory',
            old_name='used',
            new_name='thisyear_used',
        ),
        migrations.RemoveField(
            model_name='vacationhistory',
            name='created',
        ),
    ]
