# Generated by Django 2.1 on 2018-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepick', '0023_vacationhistory_workingdays_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
